[package]
name = "lc-exammanager"
version = "0.2.0"
authors = ["Dovydenkov Aleksandr <asdovydenkov@yandex.ru>"]
edition = "2021"

[dependencies]
lc-examiner = { path = "../lc-examiner" }
log = "0.4.25"
