[package]
name = "lc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "^1.3.3"
log = "0.4.25"
ntest = "0.9.3"

[dependencies.lc-examiner]
path = "../lc-examiner"

[dependencies.lc-exammanager]
path = "../lc-exammanager"
