-- Your SQL goes here
CREATE TABLE User (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR NOT NULL
);

CREATE TABLE Test (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    caption VARCHAR NOT NULL
);

CREATE TABLE Variant (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    test INTEGER NOT NULL,
    user INTEGER NOT NULL,
    mark FLOAT NOT NULL,
    start_timestamp VARCHAR NOT NULL,
    end_timestamp VARCHAR NOT NULL
);
