[package]
name = "sshtest"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "^4.5.0", features = ["derive"] }
serde_json = "1.0.97"
whoami = "1.4.0"
serde = { version = "1.0.164", features = ["derive"] }
bincode = "1.3.3"
chrono = "0.4.26"
toml = "0.7.6"


[[bin]]
name = "sshtest-daemon"
path = "src/sshtest-daemon.rs"

[[bin]]
name = "sshtest"
path = "src/sshtest.rs"

