[package]
name = "sshtest"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = {version="4.3.5", features=["derive"]}
serde_json = "1.0.97"
whoami = "1.4.0"
serde = { version = "1.0.164", features = ["derive"] }
sqlite = "0.31.0"
bincode = "1.3.3"

[[bin]]
name = "sshtest-server"
path = "src/server.rs"

[[bin]]
name = "sshtest"
path = "src/client.rs"

