tests_directory_path = "tests"
allowed_table_path = "users.csv"  

[[test]]
caption="linux"
questions_number = 2
shuffle_questions = true 
test_duration_minutes = 5
show_results = true

[[test]]
caption="python"
questions_number = 2
shuffle_questions = true 
test_duration_minutes = 5
show_results = true





