tests_directory_path = "tests"
result_path = "results"


[[test]]
caption="linux"
questions_number = 2
shuffle_questions = true 
test_duration_minutes = 5
show_results = true
allowed_users = ["asd"]
number_of_attempts = 1


[[test]]
caption="python"
questions_number = 2
shuffle_questions = true 
test_duration_minutes = 5
show_results = true
allowed_users = ["asd"]
number_of_attempts = 1


