[package]
name = "lc-examiner"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "^1.0.197", features = ["derive"] }
chrono = { version = "^0.4.35", features = ["serde"] }
log = "0.4.25"
rand = "0.8.5"
