tests_directory_path = "tests"
result_path = "results"
server_address = "127.0.0.1:65001"

[[test]]
caption="linux"
questions_number = 2
test_duration_minutes = 5
show_results = true
allowed_users = ["asd"]
number_of_attempts = 3


[[test]]
caption="python"
questions_number = 2
test_duration_minutes = 5
show_results = true
allowed_users = ["asd"]
number_of_attempts = 1


